services:
  app:
    build: .
    ports:
      - "5001:5000"  # Host port changed to 5001, container port remains 5000
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/trading_bot_db

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: